details:
  namespace: student38-bookinfo-prd
  image: ghcr.io/taninchot0919/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  host: bookinfo.opsta.net
  path: "/student38/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2